name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish ${{ matrix.package.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - name: "@mock-dash/api"
            path: packages/api
          - name: "@mock-dash/adb"
            path: packages/db
          - name: "@mock-dash/server"
            path: packages/server
    permissions:
      contents: read
      id-token: write
    if: startsWith(github.event.release.tag_name, matrix.package.name)
    steps:
      - uses: actions/checkout@v4

      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "24"
          cache: true

      - name: Install dependencies
        run: vp install

      - name: Run check
        working-directory: ${{ matrix.package.path }}
        run: vp check

      - name: Run tests
        working-directory: ${{ matrix.package.path }}
        run: vp test

      - name: Build package
        working-directory: ${{ matrix.package.path }}
        run: vp pack

      - name: Publish package to NPM with OIDC
        working-directory: ${{ matrix.package.path }}
        run: vp pm publish --no-git-checks --access public --provenance
